#!/bin/bash

printf "1234\n"|./c20 index.html -h 
mv index.html.pdm copy1.pdm
hexdump copy1.pdm > hex1
printf "1234\n"|./c20 index.html -h
mv index.html.pdm copy2.pdm
hexdump copy2.pdm > hex2
diff hex1 hex2
