#!/bin/bash
printf '1234\n' | c20 noinc -h
# printf "1234\n" | echo "${enc_p}"
# mv index.html.pdm copy1.pdm
hexdump noinc.pdm > hex1 && printf '1234\n' | c20 noinc -h
# mv index.html.pdm copy2.pdm
hexdump noinc.pdm > hex2 && diff hex1 hex2
